# Automatically generated by: ros2nix --output-as-nix-pkg-name --fetch
{ lib, buildRosPackage, fetchFromGitHub, ament-cmake-gtest, ament-cmake-ros, ament-lint-auto, ament-lint-common, lifecycle-msgs, mimick-vendor, performance-test-fixture, rcl, rcl-interfaces, rcl-lifecycle, rclcpp, rcpputils, rcutils, rmw, rosidl-typesupport-cpp, test-msgs }:
buildRosPackage rec {
  pname = "ros-rolling-rclcpp-lifecycle";
  version = "29.3.0";

  src = fetchFromGitHub {
    owner = "devsamuelv";
    repo = "rclcpp";
    rev = "9c493c4615aee3b5cbc68e9101b588564869b5dc";
    sha256 = "0m1nxkyqzfcswwwg5j1jx01bdjf9grv4nsc8dfp8mz3yw5wid9rw";
  };

  buildType = "ament_cmake";
  sourceRoot = "${src.name}/rclcpp_lifecycle/";
  buildInputs = [ ament-cmake-ros ];
  checkInputs = [ ament-cmake-gtest ament-lint-auto ament-lint-common mimick-vendor performance-test-fixture rcpputils test-msgs ];
  propagatedBuildInputs = [ lifecycle-msgs rcl rcl-interfaces rcl-lifecycle rclcpp rcutils rmw rosidl-typesupport-cpp ];
  nativeBuildInputs = [ ament-cmake-ros ];

  meta = {
    description = "Package containing a prototype for lifecycle implementation";
    license = with lib.licenses; [ asl20 ];
  };
}
