# Automatically generated by: ros2nix --output-as-nix-pkg-name --fetch
{ lib, buildRosPackage, fetchFromGitHub, action-msgs, ament-cmake-gtest, ament-cmake-ros, ament-lint-auto, ament-lint-common, mimick-vendor, performance-test-fixture, rcl, rcl-action, rclcpp, rcpputils, rosidl-runtime-c, test-msgs }:
buildRosPackage rec {
  pname = "ros-rolling-rclcpp-action";
  version = "29.3.0";

  src = fetchFromGitHub {
    owner = "devsamuelv";
    repo = "rclcpp";
    rev = "9c493c4615aee3b5cbc68e9101b588564869b5dc";
    sha256 = "0m1nxkyqzfcswwwg5j1jx01bdjf9grv4nsc8dfp8mz3yw5wid9rw";
  };

  buildType = "ament_cmake";
  sourceRoot = "${src.name}/rclcpp_action/";
  buildInputs = [ ament-cmake-ros ];
  checkInputs = [ ament-cmake-gtest ament-lint-auto ament-lint-common mimick-vendor performance-test-fixture test-msgs ];
  propagatedBuildInputs = [ action-msgs rcl rcl-action rclcpp rcpputils rosidl-runtime-c ];
  nativeBuildInputs = [ ament-cmake-ros ];

  meta = {
    description = "Adds action APIs for C++.";
    license = with lib.licenses; [ asl20 ];
  };
}
