# Automatically generated by: ros2nix --output-as-nix-pkg-name --fetch
{ lib, buildRosPackage, fetchFromGitHub, ament-cmake-google-benchmark, ament-cmake-gtest, ament-cmake-ros, ament-index-cpp, ament-lint-auto, ament-lint-common, class-loader, composition-interfaces, launch-testing, rclcpp, rcpputils, std-msgs }:
buildRosPackage rec {
  pname = "ros-rolling-rclcpp-components";
  version = "29.3.0";

  src = fetchFromGitHub {
    owner = "devsamuelv";
    repo = "rclcpp";
    rev = "9c493c4615aee3b5cbc68e9101b588564869b5dc";
    sha256 = "0m1nxkyqzfcswwwg5j1jx01bdjf9grv4nsc8dfp8mz3yw5wid9rw";
  };

  buildType = "ament_cmake";
  sourceRoot = "${src.name}/rclcpp_components/";
  buildInputs = [ ament-cmake-ros rcpputils ];
  checkInputs = [ ament-cmake-google-benchmark ament-cmake-gtest ament-lint-auto ament-lint-common launch-testing std-msgs ];
  propagatedBuildInputs = [ ament-index-cpp class-loader composition-interfaces rclcpp ];
  nativeBuildInputs = [ ament-cmake-ros ];

  meta = {
    description = "Package containing tools for dynamically loadable components";
    license = with lib.licenses; [ asl20 ];
  };
}
